export enum KycDocumentType {
  AADHAAR = "AADHAAR",
  PAN = "PAN",
  PASSPORT = "PASSPORT",
  DRIVING_LICENSE = "DRIVING_LICENSE",
  VOTER_ID = "VOTER_ID",
  BANK_STATEMENT = "BANK_STATEMENT",
  SALARY_SLIP = "SALARY_SLIP",
  CUSTOM = "CUSTOM",
}