export enum OnboardingStep {
  REGISTERED = "REGISTERED",
  OTP_VERIFIED = "OTP_VERIFIED",
  BUSINESS_SETUP = "BUSINESS_SETUP",
  KYC_UPLOADED = "KYC_UPLOADED",
  BANK_DETAILS_ADDED = "BANK_DETAILS_ADDED",
  COMPLETED = "COMPLETED",
}