export enum OnboardingStep {
  REGISTERED = "REGISTERED",
  OTP_VERIFIED = "OTP_VERIFIED",
  BUSINESS_INFO_COMPLETED = "BUSINESS_INFO_COMPLETED",
  KYC_COMPLETED = "KYC_COMPLETED",
  BANK_DETAILS_COMPLETED = "BANK_DETAILS_COMPLETED",
  COMPLETED = "COMPLETED",
}